name: Post to Twitter on Blog Update

on:
  push:
    branches:
      - main

jobs:
  tweet_post:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Check Deployment Status
      id: check_deployment
      run: |
        DEPLOYMENT_STATUS=$(curl -s -X GET "https://api.cloudflare.com/client/v4/accounts/8d5c897f2a678d10a534cee0f9cecb26/pages/projects/adnanrp/deployments" 
        -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" | jq -r '.result[0].status')
        
        echo "Deployment Status: $DEPLOYMENT_STATUS"
        
        if [[ "$DEPLOYMENT_STATUS" != "active" ]]; then
          echo "Deployment not active yet."
          exit 1 # Stop the workflow if not active
        fi

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        pip install tweepy

    - name: Run Python script to post tweet
      run: |
        python scripts/tweet_post.py
      env:
        bearer_token: ${{ secrets.bearer_token }}
        consumer_key: ${{ secrets.consumer_key }}
        consumer_secret: ${{ secrets.consumer_secret }}
        access_token: ${{ secrets.access_token }}
        token_secret: ${{ secrets.token_secret }}